on: push
name: Kurulum
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Node.js 12.x Kur
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Projeyi Derle
        run: |
          npm install
          npm run generate

      - name: FTP'ye Aktar
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.izmgamestudios.com/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASS }}
          local-dir: dist
